

name: Maven Package

on:
  push:
  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Configura Maven
      run: >
        mvn -B org.apache.maven.plugins:maven-help-plugin:3.2.0:effective-settings
        -Dmaven.repo.local=$HOME/.m2/repository
        -s bookkeeper/settings.xml

    - name: Build with Mave
      run: mvn clean install -DskipTests -Dcheckstyle.skip 



