

name: Maven Package

on:
  push:
  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


    - name: Modify Maven settings.xml
      run: |
        mkdir -p ~/.m2
        echo 'ciao' > ~/.m2/settings.xml
        
        
        
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read settings.xml
      run: |
       cat ~/.m2/settings.xml



